# Generated by Django 4.2.5 on 2023-10-15 06:58

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_alter_blogs_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='date',
            field=models.DateField(default=django.utils.datetime_safe.date.today),
        ),
    ]
