# Generated by Django 4.2.5 on 2023-10-15 10:46

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_alter_blogs_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='date',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
    ]
