# Generated by Django 4.2.5 on 2023-10-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_alter_blogs_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
