# Generated by Django 4.2.5 on 2023-10-16 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_blogs_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='date_time',
            new_name='time',
        ),
    ]
