# Generated by Django 4.2.5 on 2023-10-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_rename_date_time_blogs_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
