# Generated by Django 4.2.5 on 2023-10-19 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
