# Generated by Django 4.2.5 on 2023-11-05 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0017_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='author',
        ),
    ]
