# Generated by Django 4.2.5 on 2023-11-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0020_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='delete',
            field=models.CharField(default='حذف', max_length=20),
        ),
    ]
