# Generated by Django 4.2.5 on 2023-11-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0021_comment_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='delete',
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
