# Generated by Django 4.2.5 on 2023-11-09 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0022_remove_comment_delete_alter_comment_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
