# Generated by Django 4.2.5 on 2023-11-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_teacher_documents_alter_teacher_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='account',
            field=models.CharField(choices=[('TEACHER', 'معلم'), ('ORGANIZATIONS', 'سازمان\u200cها')], max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='payment',
            field=models.CharField(choices=[('ZARIN', 'Zarin')], max_length=100),
        ),
    ]
