# Generated by Django 4.2.5 on 2023-11-13 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_teacher_account_alter_teacher_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='account',
            field=models.CharField(choices=[('TEACHER', 'teacher'), ('ORGANIZATIONS', 'organ')], max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='userinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
