# Generated by Django 4.2.5 on 2023-10-24 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('subject', models.CharField(choices=[('medical', 'Medical'), ('nursing', 'Nursing'), ('my_uni', 'My_uni'), ('coming_soon', 'Coming_soon')], default='coming_soon', max_length=20)),
                ('date', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('upadated', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('course', 'Course'), ('special', 'Special'), ('Doing', 'doing')], default='course', max_length=10)),
                ('image', models.ImageField(blank=True, default='', upload_to='')),
                ('price', models.IntegerField(blank=True, default=0)),
                ('slug', models.SlugField(max_length=250)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('header', models.ImageField(blank=True, default='', upload_to='')),
                ('file', models.FileField(blank=True, default='', upload_to='')),
                ('prerequisite', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('about', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(blank=True, related_name='like_post', to=settings.AUTH_USER_MODEL)),
                ('recommender', models.ManyToManyField(blank=True, related_name='recommender_course', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('video', models.URLField()),
                ('summary', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
            ],
        ),
        migrations.DeleteModel(
            name='CourseInformation',
        ),
    ]
