# Generated by Django 4.2.5 on 2023-10-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_courses_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='subject',
            field=models.SlugField(choices=[('medical', 'Medical'), ('nursing', 'Nursing'), ('my_uni', 'My_uni'), ('coming_soon', 'Coming_soon')], default='coming_soon', max_length=20),
        ),
    ]
