# Generated by Django 4.2.5 on 2023-11-05 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0009_remove_courses_author_remove_courses_like_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courses',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courses',
            name='recommender',
            field=models.ManyToManyField(blank=True, default=None, related_name='recommender_course', to=settings.AUTH_USER_MODEL),
        ),
    ]
