# Generated by Django 4.2.5 on 2023-11-09 18:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0011_comment_answercomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnswerComment',
            new_name='AnswerCourseComment',
        ),
        migrations.RenameModel(
            old_name='Comment',
            new_name='CourseComment',
        ),
    ]
